### ISSUE TITLE
optimizing for speed

### ISSUE THREAD

**Issue by mariev** [ABS-dev/DiagTestKit#7]
Currently takes 10+ min each to run vignettes or examples. Need to speed this up. 

Brainstorm ideas : 
1. R data objects for fast retrieval e.g. `data.table`
2. Speedy alternative to current call to `optim()`
3. Parallel processing

**Comment by TFKentUSDA** [comment]
Commit bb3f7472 fixed this issue.  Overhaul or algorithm to for less looping and less re-computing of known values.
